
'------------------------------------------------------------------------------

' <auto-generated>

'     This code was generated from a template.

'

'     Manual changes to this file may cause unexpected behavior in your application.

'     Manual changes to this file will be overwritten if the code is regenerated.

' </auto-generated>

'------------------------------------------------------------------------------



Imports System

Imports System.Data.Entity

Imports System.Data.Entity.Infrastructure

Imports System.Data.Entity.Core.Objects

Imports System.Linq



Partial Public Class PCSRoad_DevTest_sammybranchEntities

    Inherits DbContext



    Public Sub New()

        MyBase.New("name=PCSRoad_DevTest_sammybranchEntities")

    End Sub



    Public Sub New(connectionString As String)

        MyBase.New(connectionString)

    End Sub



    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)

        Throw New UnintentionalCodeFirstException()

    End Sub





    Public Overridable Function GetPREmployeeMaster(employeeNumber As Nullable(Of Integer)) As ObjectResult(Of GetPREmployeeMaster)

        Dim employeeNumberParameter As ObjectParameter = If(employeeNumber.HasValue, New ObjectParameter("EmployeeNumber", employeeNumber), New ObjectParameter("EmployeeNumber", GetType(Integer)))



        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of GetPREmployeeMaster)("GetPREmployeeMaster", employeeNumberParameter)

    End Function



End Class